### ISSUE TITLE
Toolbox - Create suite of issue labels to help further organize our issues

### ISSUE THREAD

**Issue by DannyPeck** [CachedNerds/Toolbox#14]

**Comment by DannyPeck** [comment]
I have created a set of different issue labels.  @xmclark @technetos let me know if these work for us and if you have any objections/suggestions.

**Comment by xmclark** [comment]
I think you have covered most situations. One that came to mind is "suggestion" but I think that can be handled by "feature-request, "enhancement" or "question".

**Comment by DannyPeck** [comment]
Yeah there definitely feel like there are some missing areas.  I think suggestion is much better than feature-request to be honest.  I was also thinking about adding one along the lines of 'infrastructure' or 'organization', something to detail that it is about the process itself.  I keep finding myself choosing 'enhancement' and 'planning' and maybe other things when it could be better represented.

**Comment by DannyPeck** [comment]
I have changed type:feature-request to type:suggestion
