### ISSUE TITLE
Toolbox - Create initial milestones

### ISSUE THREAD

**Issue by DannyPeck** [CachedNerds/Toolbox#15]

**Comment by DannyPeck** [comment]
The milestones I was able to come up with were:
- Infrastructure (created)
- Logger v1.0.0 (created)
- Sink v1.0.0 (created)
- Conversion v1.0.0 (created)

Let me know if there are any other milestones that you think we should have at the moment. @xmclark @technetos

**Comment by xmclark** [comment]
I'm not too familiar with using milestones in projects. Nothing wrong about them, I'm just not familiar them.

I think these are good. Do you see all new large features or libraries having milestones? I notice you have a milestone for major releases.

**Comment by DannyPeck** [comment]
Yeah I am still not sure what the right approach is.  I added those before I added Zenhub and it feels like there are some competing features.  Milestones and Releases.  I think we should probably move the major release milestones over to be Releases and leave the Milestones for things like infrastructure, maybe reaching certain code coverage/standard goals.

**Comment by DannyPeck** [comment]
Here is a link explaining a bit about Github Milestones: https://www.zenhub.com/guides/agile-concepts-in-github#what-are-github-milestones

It states that the intent behind Milestones was to be used as Sprints.

**Comment by DannyPeck** [comment]
Here is a link about Zenhub Epics: https://www.zenhub.com/guides/agile-concepts-in-github#github-issues-as-epics

Zenhub has some good documentation about the intent of the different features and their intended use.  Epics represent large User Stories, essentially, an overarching feature that has many components and tasks that go into completing it.  I believe that the Infrastructure Milestone is an example of a Epic since there are many issues related to the Infrastructure and that we should change it to be so.  This differs from Milestones which are intended to be Sprints and are thus bound by a concept of time.

**Comment by DannyPeck** [comment]
On further inspection Zenhubs releases are really Release Reports which are meant for more managerial tracking of progress and less about tracking a Software Version Release.  We will need to decide how we wish to handle working toward a Software Version Release and we may stick with using Milestones.

**Comment by xmclark** [comment]
Sorry for late comment. 

Thanks for leaving the thoughtful comments. I also liked the links to ZenHub documentation. It helped me wrap my head around the different concepts. 

This is my big takeaway:
> I believe that the Infrastructure Milestone is an example of a Epic since there are many issues related to the Infrastructure and that we should change it to be so.  This differs from Milestones which are intended to be Sprints and are thus bound by a concept of time.

I think using milestones as releases is correct.

Regarding release numbers, I do like how Boost versions the whole library, instead of individual libraries. Since the Toolbox has some similarities, I suggest we follow that versioning plan. Their [version history](http://www.boost.org/users/history/) is really great. I recommend giving it a glance.
