### ISSUE TITLE
Toolbox - Add known supported compilers and platforms to README

### ISSUE THREAD

**Issue by xmclark** [CachedNerds/Toolbox#19]
I have tested building Logger project on the windows platform. I have not tested compiling on 

I was able to successfully compile and link Logger project using Visual Studio 2017. 

The other compilers had issues but that may have been my fault with not knowing how to compile with them on windows.

I tried compiling with g++ 5.x and I had compiler errors because of nested namespaces not being supported in that version of the compiler. I believe a later version of g++ will support these features but I didn't try them. 

I tried compiling with Clang 4.0.x and got compiler errors coming from boost. Not sure why. This should be investigated.

**Comment by DannyPeck** [comment]
Here is the output of g++ --version on my computer:

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by DannyPeck** [comment]
We need to decide what platforms & standards that we want to support throughout our entire organization and be consistent.
