### ISSUE TITLE
Toolbox - Documentation

### ISSUE THREAD

**Issue by DannyPeck** [CachedNerds/Toolbox#24]
We need to establish how we want to provide documentation for our projects.  Whether we use a tool like Doxygen or simply write ours out ourselves with some kind of pre-defined format.  Either way we need to make sure that we document our projects and keep the documentation up to date.

**Comment by technetos** [comment]
Doxygen seems fine to me.

**Comment by DannyPeck** [comment]
Here is the Doxygen manual: http://www.stack.nl/~dimitri/doxygen/manual/index.html
We should go through this and figure out what needs to go into setting this up.  I would also like to setup Doxygen with a CI system.

**Comment by DannyPeck** [comment]
We have decided to use Doxygen for our source code documentation.  We will also leverage the Github Wiki system for any additional design documentation.
