### ISSUE TITLE
Design workflow for documenation with doxygen

### ISSUE THREAD

**Issue by xmclark** [CachedNerds/Toolbox#40]
Setup a workflow for devs to use doxygen to document source code. This should be partially planning and partially documenting. Some work will just be discussion and proposal. A small document describing a devs workflow may be required.

The end goal is a clear vision of how one contributes source code with documentation. A developer should have the necessary resources to get started.

**Comment by DannyPeck** [comment]
We should also add a section or link about this in the contributing.md file.

**Comment by DannyPeck** [comment]
I'll get the ball rolling.  I believe all classes should have a comment description.  I think it's overkill for all functions/methods as a rule, but complicated or important ones should be documented.

**Comment by DannyPeck** [comment]
A documentation-standards.md file has been added and all additions to the doxygen workflow will be added there.
