### ISSUE TITLE
Determine a preferred doxygen style

### ISSUE THREAD

**Issue by xmclark** [CachedNerds/Toolbox#41]
A simple task to discuss the different styles of formatting Doxygen in source code. Research in to Doxygen syntax and configuration may be required. Some concerns are readability in source code and generated documents.

**Comment by DannyPeck** [comment]
Here is a link to the Doxygen comment format rules: [Special Blocks](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#specialblock)

**Comment by DannyPeck** [comment]
I am personally a fan of the JavaDoc syntax:
```
/**
 * Comment.
 */
```

**Comment by xmclark** [comment]
Yeah I like those too. Simplicity is good.
