### ISSUE TITLE
Research tools and how-tos on using doxgen

### ISSUE THREAD

**Issue by xmclark** [CachedNerds/Toolbox#42]
Task to research and discuss preferred tools for using Doxygen in a cross-platform way. There may be plugins, command line tools, tips and tricks, best-practices, etc. that we should be informed about.

**Comment by DannyPeck** [comment]
Here is the getting started page for Doxygen: [Getting Started](http://www.stack.nl/~dimitri/doxygen/manual/starting.html).  Here is the documentation for adding comment blocks to the source code: [Special Blocks](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#specialblock).
