### ISSUE TITLE
Sink - FileSink

### ISSUE THREAD

**Issue by DannyPeck** [CachedNerds/Toolbox#5]
We need to create a Synchronized FileSink that will allow us to log to a file.  This Sink needs to be thread-safe.  We need to also decide on what we are going to use for handling the files, ofstreams or maybe boost filesystem.  We need to research these options.

**Comment by technetos** [comment]
Why not asynchronous?

**Comment by DannyPeck** [comment]
That is my bad, I meant to say Synchronized to be thread-safe.

**Comment by DannyPeck** [comment]
The synchronization will no longer be the responsibility of the Sinks.

We should also consider making an OStreamSink instead of FileSink and be more general.. worth exploring.
